import type {
  AssetFolder,
  BenchmarkReadiness,
  ChecklistSummary,
  CommandCenterState,
  OperatorProfile,
  PlaybookItem,
  PlaybookPhase,
  SyncState,
  TrackerItem,
} from "./types";

// Seed data mirrors the canonical benchmark (June 22, 2026) and powers local demo mode.
// No secrets live here; this is safe to serve to the operator UI.

export const checklist: ChecklistSummary = {
  percent: 70,
  completed: 140,
  total: 200,
};

export const benchmark: BenchmarkReadiness = {
  baselineDate: "Jun 22, 2026",
  percent: 70,
};

export const phases: PlaybookPhase[] = [
  { id: "foundation", index: 1, name: "Foundation", completion: 90 },
  { id: "build", index: 2, name: "Build", completion: 70 },
  { id: "validate", index: 3, name: "Validate", completion: 45 },
  { id: "launch", index: 4, name: "Launch", completion: 20 },
  { id: "optimize", index: 5, name: "Optimize", completion: 0 },
];

export const items: PlaybookItem[] = [
  // Foundation Phase
  {
    id: "1.1",
    phaseId: "foundation",
    title: "Brand Voice & Messaging",
    status: "LIVE",
    execution: "Done",
    owner: "Maya S.",
    dueDate: "Jun 15, 2026",
    source: "CANONICAL",
    updated: "Jun 20, 2026",
  },
  {
    id: "1.2",
    phaseId: "foundation",
    title: "ICP & Offer Positioning",
    status: "LIVE",
    execution: "Done",
    owner: "Maya S.",
    dueDate: "Jun 10, 2026",
    source: "CANONICAL",
    updated: "Jun 18, 2026",
  },
  {
    id: "1.3",
    phaseId: "foundation",
    title: "Core Funnel Map",
    status: "LIVE",
    execution: "Done",
    owner: "Alex K.",
    dueDate: "Jun 12, 2026",
    source: "LIVE",
    updated: "Jun 18, 2026",
  },
  {
    id: "1.4",
    phaseId: "foundation",
    title: "GHL Snapshot Import v1.0",
    status: "LIVE",
    execution: "In Progress",
    owner: "Dev Team",
    dueDate: "Jun 25, 2026",
    source: "CANONICAL",
    updated: "Jun 22, 2026",
  },
  {
    id: "1.5",
    phaseId: "foundation",
    title: "Tracking Domain DNS / SSL",
    status: "LIVE",
    execution: "Done",
    owner: "Ops Team",
    dueDate: "Jun 15, 2026",
    source: "CANONICAL",
    updated: "Jun 20, 2026",
  },
  {
    id: "1.6",
    phaseId: "foundation",
    title: "Compliance Pages Setup",
    status: "DRAFT",
    execution: "In Progress",
    owner: "Riley P.",
    dueDate: "Jun 28, 2026",
    source: "DRAFT",
    updated: "Jun 22, 2026",
  },
  {
    id: "1.7",
    phaseId: "foundation",
    title: "Analytics & Conversion Tracking",
    status: "VALIDATE",
    execution: "Not Started",
    owner: "Analytics",
    dueDate: "Jun 30, 2026",
    source: "DRAFT",
    updated: "Jun 22, 2026",
  },
  {
    id: "1.8",
    phaseId: "foundation",
    title: "Partner Acquisition Funnel",
    status: "LIVE",
    execution: "Done",
    owner: "Growth Team",
    dueDate: "Jun 20, 2026",
    source: "CANONICAL",
    updated: "Jun 22, 2026",
  },
  {
    id: "1.9",
    phaseId: "foundation",
    title: "Partner Onboarding Blueprint",
    status: "LIVE",
    execution: "Done",
    owner: "Sales Enablement",
    dueDate: "Jun 18, 2026",
    source: "CANONICAL",
    updated: "Jun 22, 2026",
  },
  {
    id: "1.10",
    phaseId: "foundation",
    title: "Med Spa Demo Environment",
    status: "LIVE",
    execution: "In Progress",
    owner: "Dev Team",
    dueDate: "Jun 25, 2026",
    source: "LIVE",
    updated: "Jun 22, 2026",
  },
  {
    id: "1.11",
    phaseId: "foundation",
    title: "Client Billing Workflows",
    status: "RISK",
    execution: "Blocked",
    owner: "Ops Team",
    dueDate: "Jun 24, 2026",
    source: "CANONICAL",
    updated: "Jun 22, 2026",
  },
  {
    id: "1.12",
    phaseId: "foundation",
    title: "A2P / 10DLC Verification",
    status: "GATE",
    execution: "Not Started",
    owner: "Compliance",
    dueDate: "Jun 30, 2026",
    source: "CANONICAL",
    updated: "Jun 22, 2026",
  },
  // Build Phase
  {
    id: "2.1",
    phaseId: "build",
    title: "Lead Workflows",
    status: "LIVE",
    execution: "Done",
    owner: "Dev Team",
    dueDate: "Jun 15, 2026",
    source: "LIVE",
    updated: "Jun 20, 2026",
  },
  {
    id: "2.2",
    phaseId: "build",
    title: "Sales Workflows",
    status: "LIVE",
    execution: "Done",
    owner: "Dev Team",
    dueDate: "Jun 15, 2026",
    source: "LIVE",
    updated: "Jun 20, 2026",
  },
  {
    id: "2.3",
    phaseId: "build",
    title: "Onboarding Workflows",
    status: "LIVE",
    execution: "Done",
    owner: "Dev Team",
    dueDate: "Jun 15, 2026",
    source: "LIVE",
    updated: "Jun 20, 2026",
  },
  {
    id: "2.4",
    phaseId: "build",
    title: "Delivery Workflows",
    status: "LIVE",
    execution: "Done",
    owner: "Dev Team",
    dueDate: "Jun 15, 2026",
    source: "LIVE",
    updated: "Jun 20, 2026",
  },
  {
    id: "2.5",
    phaseId: "build",
    title: "AI Agent Workflows",
    status: "LIVE",
    execution: "Done",
    owner: "Dev Team",
    dueDate: "Jun 15, 2026",
    source: "LIVE",
    updated: "Jun 20, 2026",
  },
  {
    id: "2.6",
    phaseId: "build",
    title: "Marketing Workflows",
    status: "LIVE",
    execution: "Done",
    owner: "Dev Team",
    dueDate: "Jun 15, 2026",
    source: "LIVE",
    updated: "Jun 20, 2026",
  },
  {
    id: "2.7",
    phaseId: "build",
    title: "Billing Workflows",
    status: "RISK",
    execution: "In Progress",
    owner: "Ops Team",
    dueDate: "Jun 28, 2026",
    source: "DRAFT",
    updated: "Jun 22, 2026",
  },
  {
    id: "2.8",
    phaseId: "build",
    title: "Pipelines & Calendars",
    status: "LIVE",
    execution: "Done",
    owner: "Dev Team",
    dueDate: "Jun 15, 2026",
    source: "LIVE",
    updated: "Jun 20, 2026",
  },
  {
    id: "2.9",
    phaseId: "build",
    title: "Partner Portal Sub-Account",
    status: "DRAFT",
    execution: "Not Started",
    owner: "Dev Team",
    dueDate: "Jul 30, 2026",
    source: "DRAFT",
    updated: "Jun 22, 2026",
  },
  // Validate Phase
  {
    id: "3.1",
    phaseId: "validate",
    title: "Publish 5 Draft Demo Workflows",
    status: "GATE",
    execution: "Not Started",
    owner: "Dev Team",
    dueDate: "Jun 28, 2026",
    source: "CANONICAL",
    updated: "Jun 22, 2026",
  },
  {
    id: "3.2",
    phaseId: "validate",
    title: "Publish & Test 3 Billing Workflows",
    status: "GATE",
    execution: "Not Started",
    owner: "Ops Team",
    dueDate: "Jun 28, 2026",
    source: "CANONICAL",
    updated: "Jun 22, 2026",
  },
  {
    id: "3.3",
    phaseId: "validate",
    title: "Build 7-Email Nurture Workflow",
    status: "GATE",
    execution: "Not Started",
    owner: "Growth Team",
    dueDate: "Jun 28, 2026",
    source: "CANONICAL",
    updated: "Jun 22, 2026",
  },
  {
    id: "3.4",
    phaseId: "validate",
    title: "Connect Zoom to Partner Calendars",
    status: "RISK",
    execution: "In Progress",
    owner: "Ops Team",
    dueDate: "Jun 26, 2026",
    source: "CANONICAL",
    updated: "Jun 22, 2026",
  },
  {
    id: "3.5",
    phaseId: "validate",
    title: "Personalize Missed-Call Text",
    status: "RISK",
    execution: "In Progress",
    owner: "Dev Team",
    dueDate: "Jun 26, 2026",
    source: "CANONICAL",
    updated: "Jun 22, 2026",
  },
  {
    id: "3.6",
    phaseId: "validate",
    title: "Verify A2P / 10DLC",
    status: "RISK",
    execution: "In Progress",
    owner: "Compliance",
    dueDate: "Jun 26, 2026",
    source: "CANONICAL",
    updated: "Jun 22, 2026",
  },
  {
    id: "3.7",
    phaseId: "validate",
    title: "Blank-Account Snapshot Deploy Test",
    status: "RISK",
    execution: "In Progress",
    owner: "Dev Team",
    dueDate: "Jun 27, 2026",
    source: "CANONICAL",
    updated: "Jun 22, 2026",
  },
  {
    id: "3.8",
    phaseId: "validate",
    title: "30-Point QA Checklist",
    status: "RISK",
    execution: "In Progress",
    owner: "Ops Team",
    dueDate: "Jun 27, 2026",
    source: "CANONICAL",
    updated: "Jun 22, 2026",
  },
  // Launch Phase
  {
    id: "4.1",
    phaseId: "launch",
    title: "Organic LinkedIn Outreach",
    status: "LIVE",
    execution: "Done",
    owner: "Rob / Founder",
    dueDate: "Jun 22, 2026",
    source: "CANONICAL",
    updated: "Jun 22, 2026",
  },
  {
    id: "4.2",
    phaseId: "launch",
    title: "First Partner Field-Ready",
    status: "GATE",
    execution: "Not Started",
    owner: "Sales Enablement",
    dueDate: "Jul 30, 2026",
    source: "CANONICAL",
    updated: "Jun 22, 2026",
  },
  {
    id: "4.3",
    phaseId: "launch",
    title: "First Client Closed",
    status: "GATE",
    execution: "Not Started",
    owner: "Partner Mgr",
    dueDate: "Aug 15, 2026",
    source: "CANONICAL",
    updated: "Jun 22, 2026",
  },
  {
    id: "4.4",
    phaseId: "launch",
    title: "Paid Partner Acquisition",
    status: "VALIDATE",
    execution: "Not Started",
    owner: "Growth Team",
    dueDate: "Aug 30, 2026",
    source: "DRAFT",
    updated: "Jun 22, 2026",
  },
  // Optimize Phase
  {
    id: "5.1",
    phaseId: "optimize",
    title: "Scale Recruitment",
    status: "VALIDATE",
    execution: "Not Started",
    owner: "Growth Team",
    dueDate: "Sep 30, 2026",
    source: "DRAFT",
    updated: "Jun 22, 2026",
  },
  {
    id: "5.2",
    phaseId: "optimize",
    title: "Home Services Snapshot v1.0",
    status: "DRAFT",
    execution: "Not Started",
    owner: "Product",
    dueDate: "Sep 15, 2026",
    source: "DRAFT",
    updated: "Jun 22, 2026",
  },
  {
    id: "5.3",
    phaseId: "optimize",
    title: "Month-3 Upsell Automation",
    status: "VALIDATE",
    execution: "Not Started",
    owner: "Dev Team",
    dueDate: "Oct 15, 2026",
    source: "DRAFT",
    updated: "Jun 22, 2026",
  },
  {
    id: "5.4",
    phaseId: "optimize",
    title: "Partner Revenue Dashboard",
    status: "DRAFT",
    execution: "Not Started",
    owner: "Dev Team",
    dueDate: "Sep 30, 2026",
    source: "DRAFT",
    updated: "Jun 22, 2026",
  },
];

export const tracker: TrackerItem[] = [
  {
    id: "t1",
    title: "Publish 5 Draft Demo Workflows",
    phase: "Validate",
    dueDate: "Jun 28, 2026",
    status: "GATE",
  },
  {
    id: "t2",
    title: "Publish & Test 3 Billing Workflows",
    phase: "Validate",
    dueDate: "Jun 28, 2026",
    status: "GATE",
  },
  {
    id: "t3",
    title: "Build 7-Email Nurture Workflow",
    phase: "Build",
    dueDate: "Jun 28, 2026",
    status: "GATE",
  },
  {
    id: "t4",
    title: "Connect Zoom to Partner Calendars",
    phase: "Build",
    dueDate: "Jun 26, 2026",
    status: "RISK",
  },
  {
    id: "t5",
    title: "Personalize Missed-Call Text",
    phase: "Build",
    dueDate: "Jun 26, 2026",
    status: "RISK",
  },
  {
    id: "t6",
    title: "Verify A2P / 10DLC",
    phase: "Validate",
    dueDate: "Jun 26, 2026",
    status: "RISK",
  },
  {
    id: "t7",
    title: "Blank-Account Snapshot Deploy Test",
    phase: "Validate",
    dueDate: "Jun 27, 2026",
    status: "RISK",
  },
  {
    id: "t8",
    title: "30-Point QA Checklist",
    phase: "Validate",
    dueDate: "Jun 27, 2026",
    status: "RISK",
  },
];

export const assets: AssetFolder[] = [
  { id: "a1", name: "01 Brand & Messaging", count: 12 },
  { id: "a2", name: "02 Partner Acquisition", count: 18 },
  { id: "a3", name: "03 Sales & Demo", count: 24 },
  { id: "a4", name: "04 Niche Playbooks", count: 16 },
  { id: "a5", name: "05 Workflows & Automations", count: 20 },
  { id: "a6", name: "06 Onboarding & Training", count: 14 },
  { id: "a7", name: "07 Compliance & Legal", count: 10 },
  { id: "a8", name: "08 Reporting & Analytics", count: 8 },
];

export const sync: SyncState = {
  message: "All changes synced 2m ago",
  storage: "Cloud",
  sourceOfTruth: "CANONICAL",
};

export const operator: OperatorProfile = {
  name: "LixenAI Ops",
  org: "LixenAI Team",
  initials: "LO",
};

export function getCommandCenterState(): CommandCenterState {
  return {
    checklist,
    benchmark,
    phases,
    items,
    tracker,
    assets,
    sync,
    operator,
  };
}